export const parkingOptionsData = [
  {
    id: 1,
    title: "Park and Ride",
    desc1: "2 miles from the Airport",
    desc2: "20 minutes transfer",
    desc3: "Can be cancelled",
    price: "£5 / hour",
  },
  {
    id: 2,
    title: "Meet and Greet",
    desc1: "Valet Parking",
    desc2: "Arrive At The Terminal",
    desc3: "Can be cancelled",
    price: "£15 / hour",
  },
  {
    id: 3,
    title: "Park and Ride",
    desc1: "4 miles from the Airport",
    desc2: "20 minutes transfer",
    desc3: "Can be cancelled",
    price: "£25 / day",
  },
  {
    id: 4,
    title: "Meet and Greet",
    desc1: "Valet Parking",
    desc2: "Arrive At The Terminal",
    desc3: "Can be cancelled",
    price: "£35 / day",
  },
  {
    id: 5,
    title: "Park and Ride",
    desc1: "3 miles from the Airport",
    desc2: "20 minutes transfer",
    desc3: "Can be cancelled",
    price: "£120 / week",
  },
  {
    id: 6,
    title: "Meet and Greet",
    desc1: "Premium Valet",
    desc2: "Arrive At The Terminal",
    desc3: "Can be cancelled",
    price: "£200 / week",
  },
];
